### ISSUE TITLE
python3 straight_lane_agent_c51_training.py

### ISSUE THREAD

**Issue by yihsinma** [kochlisGit/autonomous-vehicles-agent#8]
How to solve this problem?
(Autonomous-vehicle) ma@ma-ROG-Strix:~/Desktop/carla/PythonAPI/Autonomous-Vehicles-Adaptive-Cruise-Control/code/agent$ python3 straight_lane_agent_c51_training.py
2023-12-05 15:28:04.402854: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-05 15:28:04.466888: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-05 15:28:04.868101: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64:/home/ma/carla-ros-bridge1/catkin_ws/devel/lib:/opt/ros/noetic/lib
2023-12-05 15:28:04.868145: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64:/home/ma/carla-ros-bridge1/catkin_ws/devel/lib:/opt/ros/noetic/lib
2023-12-05 15:28:04.868149: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "straight_lane_agent_c51_training.py", line 34, in <module>
    from environment.carla_environment import CarlaEnvironment
ModuleNotFoundError: No module named 'environment.carla_environment'; 'environment' is not a package

**Comment by kochlisGit** [comment]
1. Can you verify that you downloaded file 'environment.carla_environment'"
2. Run the script from the main directory.

**Comment by yihsinma** [comment]
> 1. Can you verify that you downloaded file 'environment.carla_environment'"
> 2. Run the script from the main directory.

1.Is Autonomous-Vehicles-Adaptive-Cruise-Control/code/environment/carla_environment.py？
2.I already run the script from the main directory.
(Autonomous-vehicle) ma@ma-ROG-Strix:~/Desktop/carla/PythonAPI/Autonomous-Vehicles-Adaptive-Cruise-Control/code$ python3 agent/straight_lane_agent_c51_training.py 
2023-12-06 11:01:50.393363: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-06 11:01:50.464727: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-06 11:01:50.878229: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64:/home/ma/carla-ros-bridge1/catkin_ws/devel/lib:/opt/ros/noetic/lib
2023-12-06 11:01:50.878272: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64:/home/ma/carla-ros-bridge1/catkin_ws/devel/lib:/opt/ros/noetic/lib
2023-12-06 11:01:50.878277: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "agent/straight_lane_agent_c51_training.py", line 34, in <module>
    from environment.carla_environment import CarlaEnvironment
ModuleNotFoundError: No module named 'environment.carla_environment'; 'environment' is not a package

**Comment by kochlisGit** [comment]
For some reason it cannot find environment folder. Once you download the repository, make sure all scripts run inside "code" folder, where environment folder is visible.

**Comment by yihsinma** [comment]
> 由於某種原因，它找不到環境資料夾。下載儲存庫後，請確保所有腳本在「code」資料夾中運行，其中環境資料夾可見。

I execute them all under code,Is there any solution?

**Comment by kochlisGit** [comment]
Well, the repository is kinda old, so I'd suggest check out the new one:
https://github.com/kochlisGit/Noise-Adaptive-Driving-Assistance-System

It is better and easier to train!
